### ISSUE TITLE
space-time attention

### ISSUE THREAD

**Issue by isyangshu** [sbasu276/FocusMAE#2]
Congratulations on your outstanding work!

You said "We employed avanilla ViT architecture with space-time attention (TimeSformer)" in this paper. I wonder if you use the joint space-time attention or divided space-time attention. From "pretrain_focusmae_small_patch_base_model" and "vit_base_patch16_224", I noticed you use the joint space-time attention. 

Thanks for your attention and reply.

**Comment by sbasu276** [comment]
Hi, thanks for your interest in our work. Yes, we have indeed used the joint space-time attention in our work.
